-- Migration 0009: Schema Update and Real Stickers Seed

-- 1. Alter schema
ALTER TABLE stickers ADD COLUMN IF NOT EXISTS group_name TEXT;
ALTER TABLE stickers ADD COLUMN IF NOT EXISTS team_name TEXT;

-- 2. Wipe old dummy data 
DELETE FROM trade_items;
DELETE FROM trades;
DELETE FROM user_inventory;
DELETE FROM stickers;

-- 3. Insert real data
INSERT INTO stickers (code, name, team_name, group_name) VALUES
('MEX-1', 'Luis Malagón', 'México', 'Grupo A'),
('MEX-2', 'Johan Vásquez', 'México', 'Grupo A'),
('MEX-3', 'Jorge Sánchez', 'México', 'Grupo A'),
('MEX-4', 'César Montes', 'México', 'Grupo A'),
('MEX-5', 'Jesús Gallardo', 'México', 'Grupo A'),
('MEX-6', 'Israel Reyes', 'México', 'Grupo A'),
('MEX-7', 'Diego Lainez', 'México', 'Grupo A'),
('MEX-8', 'Carlos Rodríguez', 'México', 'Grupo A'),
('MEX-9', 'Edson Álvarez', 'México', 'Grupo A'),
('MEX-10', 'Orbelín Pineda', 'México', 'Grupo A'),
('MEX-11', 'Marcel Ruiz', 'México', 'Grupo A'),
('MEX-12', 'Érick Sánchez', 'México', 'Grupo A'),
('MEX-13', 'Hirving Lozano', 'México', 'Grupo A'),
('MEX-14', 'Santiago Giménez', 'México', 'Grupo A'),
('MEX-15', 'Raúl Jiménez', 'México', 'Grupo A'),
('MEX-16', 'Alexis Vega', 'México', 'Grupo A'),
('MEX-17', 'Roberto Alvarado', 'México', 'Grupo A'),
('MEX-18', 'César Huerta', 'México', 'Grupo A'),
('RSA-1', 'Ronwen Williams', 'África do Sul', 'Grupo A'),
('RSA-2', 'Sipho Chaine', 'África do Sul', 'Grupo A'),
('RSA-3', 'Aubrey Modiba', 'África do Sul', 'Grupo A'),
('RSA-4', 'Samukele Kabini', 'África do Sul', 'Grupo A'),
('RSA-5', 'Mbekezeli Mbokazi', 'África do Sul', 'Grupo A'),
('RSA-6', 'Khulumani Ndamane', 'África do Sul', 'Grupo A'),
('RSA-7', 'Siyabonga Ngezana', 'África do Sul', 'Grupo A'),
('RSA-8', 'Khuliso Mudau', 'África do Sul', 'Grupo A'),
('RSA-9', 'Nkosinathi Sibisi', 'África do Sul', 'Grupo A'),
('RSA-10', 'Teboho Mokoena', 'África do Sul', 'Grupo A'),
('RSA-11', 'Thalente Mbatha', 'África do Sul', 'Grupo A'),
('RSA-12', 'Bathuisi Aubaas', 'África do Sul', 'Grupo A'),
('RSA-13', 'Yaya Sithole', 'África do Sul', 'Grupo A'),
('RSA-14', 'Sipho Mbule', 'África do Sul', 'Grupo A'),
('RSA-15', 'Lyle Foster', 'África do Sul', 'Grupo A'),
('RSA-16', 'Ioraam Rayners', 'África do Sul', 'Grupo A'),
('RSA-17', 'Mohau Nkota', 'África do Sul', 'Grupo A'),
('RSA-18', 'Oswin Appolis', 'África do Sul', 'Grupo A'),
('KOR-1', 'Hyeon-woo Jo', 'Coreia do Sul', 'Grupo A'),
('KOR-2', 'Seung-Gyu Kim', 'Coreia do Sul', 'Grupo A'),
('KOR-3', 'Min-jae Kim', 'Coreia do Sul', 'Grupo A'),
('KOR-4', 'Yu-min Cho', 'Coreia do Sul', 'Grupo A'),
('KOR-5', 'Young-woo Seol', 'Coreia do Sul', 'Grupo A'),
('KOR-6', 'Han-beom Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-7', 'Tae-seok Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-8', 'Myung-jae Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-9', 'Jae-sung Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-10', 'In-beom Hwang', 'Coreia do Sul', 'Grupo A'),
('KOR-11', 'Kang-in Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-12', 'Seung-ho Paik', 'Coreia do Sul', 'Grupo A'),
('KOR-13', 'Jens Castrop', 'Coreia do Sul', 'Grupo A'),
('KOR-14', 'Dong-gyeong Lee', 'Coreia do Sul', 'Grupo A'),
('KOR-15', 'Gue-sung Cho', 'Coreia do Sul', 'Grupo A'),
('KOR-16', 'Heung-min Son', 'Coreia do Sul', 'Grupo A'),
('KOR-17', 'Hee-chan Hwang', 'Coreia do Sul', 'Grupo A'),
('KOR-18', 'Hyeon-Gyu Oh', 'Coreia do Sul', 'Grupo A'),
('CZE-1', 'Matěj Kovář', 'República Tcheca', 'Grupo A'),
('CZE-2', 'Jindřich Staněk', 'República Tcheca', 'Grupo A'),
('CZE-3', 'Ladislav Krejčí', 'República Tcheca', 'Grupo A'),
('CZE-4', 'Vladimír Coufal', 'República Tcheca', 'Grupo A'),
('CZE-5', 'Jaroslav Zelený', 'República Tcheca', 'Grupo A'),
('CZE-6', 'Tomáš Holeš', 'República Tcheca', 'Grupo A'),
('CZE-7', 'David Zima', 'República Tcheca', 'Grupo A'),
('CZE-8', 'Michal Sadílek', 'República Tcheca', 'Grupo A'),
('CZE-9', 'Lukáš Provod', 'República Tcheca', 'Grupo A'),
('CZE-10', 'Lukáš Červ', 'República Tcheca', 'Grupo A'),
('CZE-11', 'Tomáš Souček', 'República Tcheca', 'Grupo A'),
('CZE-12', 'Pavel Šulc', 'República Tcheca', 'Grupo A'),
('CZE-13', 'Matěj Vydra', 'República Tcheca', 'Grupo A'),
('CZE-14', 'Vasil Kušej', 'República Tcheca', 'Grupo A'),
('CZE-15', 'Tomáš Chorý', 'República Tcheca', 'Grupo A'),
('CZE-16', 'Václav Černý', 'República Tcheca', 'Grupo A'),
('CZE-17', 'Adam Hložek', 'República Tcheca', 'Grupo A'),
('CZE-18', 'Patrik Schick', 'República Tcheca', 'Grupo A'),
('CAN-1', 'Dayne St. Clair', 'Canadá', 'Grupo B'),
('CAN-2', 'Alphonso Davies', 'Canadá', 'Grupo B'),
('CAN-3', 'Alistair Johnston', 'Canadá', 'Grupo B'),
('CAN-4', 'Samuel Adekugbe', 'Canadá', 'Grupo B'),
('CAN-5', 'Richie Laryea', 'Canadá', 'Grupo B'),
('CAN-6', 'Derek Cornelius', 'Canadá', 'Grupo B'),
('CAN-7', 'Moïse Bombito', 'Canadá', 'Grupo B'),
('CAN-8', 'Kamal Miller', 'Canadá', 'Grupo B'),
('CAN-9', 'Stephen Eustáquio', 'Canadá', 'Grupo B'),
('CAN-10', 'Ismaël Koné', 'Canadá', 'Grupo B'),
('CAN-11', 'Jonathan Osorio', 'Canadá', 'Grupo B'),
('CAN-12', 'Jacob Shaffelburg', 'Canadá', 'Grupo B'),
('CAN-13', 'Mathieu Choinière', 'Canadá', 'Grupo B'),
('CAN-14', 'Niko Sigur', 'Canadá', 'Grupo B'),
('CAN-15', 'Tajon Buchanan', 'Canadá', 'Grupo B'),
('CAN-16', 'Liam Millar', 'Canadá', 'Grupo B'),
('CAN-17', 'Cyle Larin', 'Canadá', 'Grupo B'),
('CAN-18', 'Jonathan David', 'Canadá', 'Grupo B'),
('BIH-1', 'Nikola Vasilj', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-2', 'Amar Dedić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-3', 'Sead Kolašinac', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-4', 'Tarik Muharemović', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-5', 'Nihad Mujakić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-6', 'Nikola Katić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-7', 'Amir Hadžiahmetović', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-8', 'Benjamin Tahirović', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-9', 'Armin Gigović', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-10', 'Ivan Šunjić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-11', 'Ivan Bašić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-12', 'Dženis Burnić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-13', 'Esmir Bajraktarević', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-14', 'Amar Memić', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-15', 'Ermedin Demirović', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-16', 'Edin Džeko', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-17', 'Samed Baždar', 'Bósnia e Herzegovina', 'Grupo B'),
('BIH-18', 'Haris Tabaković', 'Bósnia e Herzegovina', 'Grupo B'),
('QAT-1', 'Meshaal Barsham', 'Catar', 'Grupo B'),
('QAT-2', 'Sultan Albrake', 'Catar', 'Grupo B'),
('QAT-3', 'Lucas Mendes', 'Catar', 'Grupo B'),
('QAT-4', 'Homam Ahmed', 'Catar', 'Grupo B'),
('QAT-5', 'Boualem Khoukhi', 'Catar', 'Grupo B'),
('QAT-6', 'Pedro Miguel', 'Catar', 'Grupo B'),
('QAT-7', 'Tarek Salman', 'Catar', 'Grupo B'),
('QAT-8', 'Mohamed Al-Mannai', 'Catar', 'Grupo B'),
('QAT-9', 'Karim Boudiaf', 'Catar', 'Grupo B'),
('QAT-10', 'Assim Madibo', 'Catar', 'Grupo B'),
('QAT-11', 'Ahmed Fatehi', 'Catar', 'Grupo B'),
('QAT-12', 'Mohammed Waad', 'Catar', 'Grupo B'),
('QAT-13', 'Abdulaziz Hatem', 'Catar', 'Grupo B'),
('QAT-14', 'Hassan Al-Haydos', 'Catar', 'Grupo B'),
('QAT-15', 'Edmilson Junior', 'Catar', 'Grupo B'),
('QAT-16', 'Akram Hassan Afif', 'Catar', 'Grupo B'),
('QAT-17', 'Ahmed Al Ganehi', 'Catar', 'Grupo B'),
('QAT-18', 'Almoez Ali', 'Catar', 'Grupo B'),
('SUI-1', 'Gregor Kobel', 'Suíça', 'Grupo B'),
('SUI-2', 'Yvon Mvogo', 'Suíça', 'Grupo B'),
('SUI-3', 'Manuel Akanji', 'Suíça', 'Grupo B'),
('SUI-4', 'Ricardo Rodriguez', 'Suíça', 'Grupo B'),
('SUI-5', 'Nico Elvedi', 'Suíça', 'Grupo B'),
('SUI-6', 'Aurèle Amenda', 'Suíça', 'Grupo B'),
('SUI-7', 'Silvan Widmer', 'Suíça', 'Grupo B'),
('SUI-8', 'Granit Xhaka', 'Suíça', 'Grupo B'),
('SUI-9', 'Denis Zakaria', 'Suíça', 'Grupo B'),
('SUI-10', 'Remo Freuler', 'Suíça', 'Grupo B'),
('SUI-11', 'Fabian Rieder', 'Suíça', 'Grupo B'),
('SUI-12', 'Ardon Jashari', 'Suíça', 'Grupo B'),
('SUI-13', 'Johan Manzambi', 'Suíça', 'Grupo B'),
('SUI-14', 'Michel Aebischer', 'Suíça', 'Grupo B'),
('SUI-15', 'Breel Embolo', 'Suíça', 'Grupo B'),
('SUI-16', 'Ruben Vargas', 'Suíça', 'Grupo B'),
('SUI-17', 'Dan Ndoye', 'Suíça', 'Grupo B'),
('SUI-18', 'Zeki Amdouni', 'Suíça', 'Grupo B'),
('BRA-1', 'Alisson', 'Brasil', 'Grupo C'),
('BRA-2', 'Bento', 'Brasil', 'Grupo C'),
('BRA-3', 'Marquinhos', 'Brasil', 'Grupo C'),
('BRA-4', 'Éder Militão', 'Brasil', 'Grupo C'),
('BRA-5', 'Gabriel Magalhães', 'Brasil', 'Grupo C'),
('BRA-6', 'Danilo', 'Brasil', 'Grupo C'),
('BRA-7', 'Wesley', 'Brasil', 'Grupo C'),
('BRA-8', 'Lucas Paquetá', 'Brasil', 'Grupo C'),
('BRA-9', 'Casemiro', 'Brasil', 'Grupo C'),
('BRA-10', 'Bruno Guimarães', 'Brasil', 'Grupo C'),
('BRA-11', 'Luiz Henrique', 'Brasil', 'Grupo C'),
('BRA-12', 'Vinícius Júnior', 'Brasil', 'Grupo C'),
('BRA-13', 'Rodrygo', 'Brasil', 'Grupo C'),
('BRA-14', 'João Pedro', 'Brasil', 'Grupo C'),
('BRA-15', 'Matheus Cunha', 'Brasil', 'Grupo C'),
('BRA-16', 'Gabriel Martinelli', 'Brasil', 'Grupo C'),
('BRA-17', 'Raphinha', 'Brasil', 'Grupo C'),
('BRA-18', 'Estêvão', 'Brasil', 'Grupo C'),
('MAR-1', 'Yassine Bounou', 'Marrocos', 'Grupo C'),
('MAR-2', 'Munir El Kajoui', 'Marrocos', 'Grupo C'),
('MAR-3', 'Achraf Hakimi', 'Marrocos', 'Grupo C'),
('MAR-4', 'Noussair Mazraoui', 'Marrocos', 'Grupo C'),
('MAR-5', 'Nayef Aguerd', 'Marrocos', 'Grupo C'),
('MAR-6', 'Romain Saïss', 'Marrocos', 'Grupo C'),
('MAR-7', 'Jawad El Yamiq', 'Marrocos', 'Grupo C'),
('MAR-8', 'Adam Masina', 'Marrocos', 'Grupo C'),
('MAR-9', 'Sofyan Amrabat', 'Marrocos', 'Grupo C'),
('MAR-10', 'Azzedine Ounahi', 'Marrocos', 'Grupo C'),
('MAR-11', 'Eliesse Ben Seghir', 'Marrocos', 'Grupo C'),
('MAR-12', 'Bilal El Khannouss', 'Marrocos', 'Grupo C'),
('MAR-13', 'Ismael Saibari', 'Marrocos', 'Grupo C'),
('MAR-14', 'Youssef En-Nesyri', 'Marrocos', 'Grupo C'),
('MAR-15', 'Abde Ezzalzouli', 'Marrocos', 'Grupo C'),
('MAR-16', 'Soufiane Rahimi', 'Marrocos', 'Grupo C'),
('MAR-17', 'Brahim Díaz', 'Marrocos', 'Grupo C'),
('MAR-18', 'Ayoub El Kaabi', 'Marrocos', 'Grupo C'),
('HAI-1', 'Johny Placide', 'Haiti', 'Grupo C'),
('HAI-2', 'Carlens Arcus', 'Haiti', 'Grupo C'),
('HAI-3', 'Martin Expérience', 'Haiti', 'Grupo C'),
('HAI-4', 'Jean-Kevin Duverne', 'Haiti', 'Grupo C'),
('HAI-5', 'Ricardo Adé', 'Haiti', 'Grupo C'),
('HAI-6', 'Duke Lacroix', 'Haiti', 'Grupo C'),
('HAI-7', 'Garven Metusala', 'Haiti', 'Grupo C'),
('HAI-8', 'Hannes Delcroix', 'Haiti', 'Grupo C'),
('HAI-9', 'Leverton Pierre', 'Haiti', 'Grupo C'),
('HAI-10', 'Danley Jean Jacques', 'Haiti', 'Grupo C'),
('HAI-11', 'Jean-Ricner Bellegarde', 'Haiti', 'Grupo C'),
('HAI-12', 'Christopher Attys', 'Haiti', 'Grupo C'),
('HAI-13', 'Derrick Etienne Jr.', 'Haiti', 'Grupo C'),
('HAI-14', 'Josué Casimir', 'Haiti', 'Grupo C'),
('HAI-15', 'Ruben Providence', 'Haiti', 'Grupo C'),
('HAI-16', 'Duckens Nazon', 'Haiti', 'Grupo C'),
('HAI-17', 'Louicius Deedson', 'Haiti', 'Grupo C'),
('HAI-18', 'Frantzdy Pierrot', 'Haiti', 'Grupo C'),
('SCO-1', 'Angus Gunn', 'Escócia', 'Grupo C'),
('SCO-2', 'Jack Hendry', 'Escócia', 'Grupo C'),
('SCO-3', 'Kieran Tierney', 'Escócia', 'Grupo C'),
('SCO-4', 'Aaron Hickey', 'Escócia', 'Grupo C'),
('SCO-5', 'Andrew Robertson', 'Escócia', 'Grupo C'),
('SCO-6', 'Scott McKenna', 'Escócia', 'Grupo C'),
('SCO-7', 'John Souttar', 'Escócia', 'Grupo C'),
('SCO-8', 'Anthony Ralston', 'Escócia', 'Grupo C'),
('SCO-9', 'Grant Hanley', 'Escócia', 'Grupo C'),
('SCO-10', 'Scott McTominay', 'Escócia', 'Grupo C'),
('SCO-11', 'Billy GilmourLewis', 'Escócia', 'Grupo C'),
('SCO-12', 'Ferguson', 'Escócia', 'Grupo C'),
('SCO-13', 'Ryan Christie', 'Escócia', 'Grupo C'),
('SCO-14', 'Kenny McLean', 'Escócia', 'Grupo C'),
('SCO-15', 'John McGinn', 'Escócia', 'Grupo C'),
('SCO-16', 'Lyndon Dykes', 'Escócia', 'Grupo C'),
('SCO-17', 'Che Adams', 'Escócia', 'Grupo C'),
('SCO-18', 'Ben Gannon-Doak', 'Escócia', 'Grupo C'),
('USA-1', 'Math Freese', 'Estados Unidos', 'Grupo D'),
('USA-2', 'Chris Richards', 'Estados Unidos', 'Grupo D'),
('USA-3', 'Tim Ream', 'Estados Unidos', 'Grupo D'),
('USA-4', 'Mark McKenzie', 'Estados Unidos', 'Grupo D'),
('USA-5', 'Alex Freeman', 'Estados Unidos', 'Grupo D'),
('USA-6', 'Antonee Robinson', 'Estados Unidos', 'Grupo D'),
('USA-7', 'Tyler Adams', 'Estados Unidos', 'Grupo D'),
('USA-8', 'Tanner Tessmann', 'Estados Unidos', 'Grupo D'),
('USA-9', 'Weston McKenny', 'Estados Unidos', 'Grupo D'),
('USA-10', 'Christian Roldan', 'Estados Unidos', 'Grupo D'),
('USA-11', 'Timothy Weah', 'Estados Unidos', 'Grupo D'),
('USA-12', 'Diego Luna', 'Estados Unidos', 'Grupo D'),
('USA-13', 'Malim Tillman', 'Estados Unidos', 'Grupo D'),
('USA-14', 'Christian Pulisic', 'Estados Unidos', 'Grupo D'),
('USA-15', 'Brenden Aaronson', 'Estados Unidos', 'Grupo D'),
('USA-16', 'Ricardo Pepi', 'Estados Unidos', 'Grupo D'),
('USA-17', 'Haji Wright', 'Estados Unidos', 'Grupo D'),
('USA-18', 'Folarin Balogun', 'Estados Unidos', 'Grupo D'),
('PAR-1', 'Roberto Fernández', 'Paraguai', 'Grupo D'),
('PAR-2', 'Orlando Gill', 'Paraguai', 'Grupo D'),
('PAR-3', 'Gustavo Gómez', 'Paraguai', 'Grupo D'),
('PAR-4', 'Fabián Balbuena', 'Paraguai', 'Grupo D'),
('PAR-5', 'Juan José Cáceres', 'Paraguai', 'Grupo D'),
('PAR-6', 'Omar Alderete', 'Paraguai', 'Grupo D'),
('PAR-7', 'Junior Alonso', 'Paraguai', 'Grupo D'),
('PAR-8', 'Mathías Villasanti', 'Paraguai', 'Grupo D'),
('PAR-9', 'Diego Gómez', 'Paraguai', 'Grupo D'),
('PAR-10', 'Damián Bobadilla', 'Paraguai', 'Grupo D'),
('PAR-11', 'Andrés Cubas', 'Paraguai', 'Grupo D'),
('PAR-12', 'Matías Galarza Fonda', 'Paraguai', 'Grupo D'),
('PAR-13', 'Julio Enciso', 'Paraguai', 'Grupo D'),
('AUS-1', 'Mathew Ryan', 'Austrália', 'Grupo D'),
('AUS-2', 'Joe Gauci', 'Austrália', 'Grupo D'),
('AUS-3', 'Harry Souttar', 'Austrália', 'Grupo D'),
('AUS-4', 'Alessandro Circati', 'Austrália', 'Grupo D'),
('AUS-5', 'Jordan Bos', 'Austrália', 'Grupo D'),
('AUS-6', 'Aziz Behich', 'Austrália', 'Grupo D'),
('AUS-7', 'Cameron Burgess', 'Austrália', 'Grupo D'),
('AUS-8', 'Lewis Miller', 'Austrália', 'Grupo D'),
('AUS-9', 'Milos Degenek', 'Austrália', 'Grupo D'),
('AUS-10', 'Jackson Irvine', 'Austrália', 'Grupo D'),
('AUS-11', 'Riley McGree', 'Austrália', 'Grupo D'),
('AUS-12', 'Aiden O’Neill', 'Austrália', 'Grupo D'),
('AUS-13', 'Connor Metcalfe', 'Austrália', 'Grupo D'),
('AUS-14', 'Patrick Yazbek', 'Austrália', 'Grupo D'),
('AUS-15', 'Craig Goodwin', 'Austrália', 'Grupo D'),
('AUS-16', 'Kusini Yengi', 'Austrália', 'Grupo D'),
('AUS-17', 'Nestory Irankunda', 'Austrália', 'Grupo D'),
('AUS-18', 'Mohamed Touré', 'Austrália', 'Grupo D'),
('TUR-1', 'Ugurcan Cakir', 'Turquia', 'Grupo D'),
('TUR-2', 'Mert Muldur', 'Turquia', 'Grupo D'),
('TUR-3', 'Zeki Celik', 'Turquia', 'Grupo D'),
('TUR-4', 'Abdulkerim Bardakci', 'Turquia', 'Grupo D'),
('TUR-5', 'Caglar Soyunku', 'Turquia', 'Grupo D'),
('TUR-6', 'Merih Demiral', 'Turquia', 'Grupo D'),
('TUR-7', 'Ferdi Kadioglu', 'Turquia', 'Grupo D'),
('TUR-8', 'Kaan Ayhan', 'Turquia', 'Grupo D'),
('TUR-9', 'Ismail Yuksek', 'Turquia', 'Grupo D'),
('TUR-10', 'Hakan Calhanoglu', 'Turquia', 'Grupo D'),
('TUR-11', 'Orkun Kokcu', 'Turquia', 'Grupo D'),
('TUR-12', 'Arda Güler', 'Turquia', 'Grupo D'),
('TUR-13', 'Irfan Can Kahvecu', 'Turquia', 'Grupo D'),
('TUR-14', 'Yunus Akgun', 'Turquia', 'Grupo D'),
('TUR-15', 'Can Uzun', 'Turquia', 'Grupo D'),
('TUR-16', 'Baris Alper Yilmaz', 'Turquia', 'Grupo D'),
('TUR-17', 'Kerem Akturkoglu', 'Turquia', 'Grupo D'),
('TUR-18', 'Kenan Yildiz', 'Turquia', 'Grupo D'),
('GER-1', 'Marc-André ter Stegen', 'Alemanha', 'Grupo E'),
('GER-2', 'Jonathan Tah', 'Alemanha', 'Grupo E'),
('GER-3', 'David Raum', 'Alemanha', 'Grupo E'),
('GER-4', 'Nico Schlotterbeck', 'Alemanha', 'Grupo E'),
('GER-5', 'Antonio Rüdiger', 'Alemanha', 'Grupo E'),
('GER-6', 'Waldemar Anton', 'Alemanha', 'Grupo E'),
('GER-7', 'Ridle Baku', 'Alemanha', 'Grupo E'),
('GER-8', 'Maximilian Mittelstädt', 'Alemanha', 'Grupo E'),
('GER-9', 'Joshua Kimmich', 'Alemanha', 'Grupo E'),
('GER-10', 'Florian Wirtz', 'Alemanha', 'Grupo E'),
('GER-11', 'Felix Nmecha', 'Alemanha', 'Grupo E'),
('GER-12', 'Leon Goretzka', 'Alemanha', 'Grupo E'),
('GER-13', 'Jamal Musiala', 'Alemanha', 'Grupo E'),
('GER-14', 'Serge Gnabry', 'Alemanha', 'Grupo E'),
('GER-15', 'Kai Havertz', 'Alemanha', 'Grupo E'),
('GER-16', 'Leroy Sané', 'Alemanha', 'Grupo E'),
('GER-17', 'Karim Adeyemi', 'Alemanha', 'Grupo E'),
('GER-18', 'Nick Woltemade', 'Alemanha', 'Grupo E'),
('CUW-1', 'Eloy Room', 'Curaçao', 'Grupo E'),
('CUW-2', 'Armando Obispo', 'Curaçao', 'Grupo E'),
('CUW-3', 'Sherel Floranus', 'Curaçao', 'Grupo E'),
('CUW-4', 'Jurien Gaari', 'Curaçao', 'Grupo E'),
('CUW-5', 'Joshua Brenet', 'Curaçao', 'Grupo E'),
('CUW-6', 'Roshon Van Eijma', 'Curaçao', 'Grupo E'),
('CUW-7', 'Shurandy Sambo', 'Curaçao', 'Grupo E'),
('CUW-8', 'Livano Comenencia', 'Curaçao', 'Grupo E'),
('CUW-9', 'Godfried Roemeratoe', 'Curaçao', 'Grupo E'),
('CUW-10', 'Juninho Bacuna', 'Curaçao', 'Grupo E'),
('CUW-11', 'Leandro Bacuna', 'Curaçao', 'Grupo E'),
('CUW-12', 'Tahith Chong', 'Curaçao', 'Grupo E'),
('CUW-13', 'Kenji Gorré', 'Curaçao', 'Grupo E'),
('CUW-14', 'Jearl Margaritha', 'Curaçao', 'Grupo E'),
('CUW-15', 'Jurgen Locadia', 'Curaçao', 'Grupo E'),
('CUW-16', 'Jeremy Antonisse', 'Curaçao', 'Grupo E'),
('CUW-17', 'Gervane Kastaneer', 'Curaçao', 'Grupo E'),
('CUW-18', 'Sontje Hansen', 'Curaçao', 'Grupo E'),
('CIV-1', 'Yahia Fofana', 'Costa do Marfim', 'Grupo E'),
('CIV-2', 'Ghislain Konan', 'Costa do Marfim', 'Grupo E'),
('CIV-3', 'Wilfried Singo', 'Costa do Marfim', 'Grupo E'),
('CIV-4', 'Odilon Kossounou', 'Costa do Marfim', 'Grupo E'),
('CIV-5', 'Evan Ndicka', 'Costa do Marfim', 'Grupo E'),
('CIV-6', 'Willy Boly', 'Costa do Marfim', 'Grupo E'),
('CIV-7', 'Emmanuel Agbadou', 'Costa do Marfim', 'Grupo E'),
('CIV-8', 'Ousmane Diomande', 'Costa do Marfim', 'Grupo E'),
('CIV-9', 'Franck Kessié', 'Costa do Marfim', 'Grupo E'),
('CIV-10', 'Seko Fofana', 'Costa do Marfim', 'Grupo E'),
('CIV-11', 'Ibrahim Sangaré', 'Costa do Marfim', 'Grupo E'),
('CIV-12', 'Jean-Philippe Gbamin', 'Costa do Marfim', 'Grupo E'),
('CIV-13', 'Amad Diallo', 'Costa do Marfim', 'Grupo E'),
('CIV-14', 'Sébastien Haller', 'Costa do Marfim', 'Grupo E'),
('CIV-15', 'Simon Adingra', 'Costa do Marfim', 'Grupo E'),
('CIV-16', 'Yan Diomande', 'Costa do Marfim', 'Grupo E'),
('CIV-17', 'Evann Guessand', 'Costa do Marfim', 'Grupo E'),
('CIV-18', 'Oumar Diakité', 'Costa do Marfim', 'Grupo E'),
('ECU-1', 'Hernán Galíndez', 'Equador', 'Grupo E'),
('ECU-2', 'Gonzalo Valle', 'Equador', 'Grupo E'),
('ECU-3', 'Piero Hincapié', 'Equador', 'Grupo E'),
('ECU-4', 'Pervis Estupiñán', 'Equador', 'Grupo E'),
('ECU-5', 'Willian Pacho', 'Equador', 'Grupo E'),
('ECU-6', 'Ángelo Preciado', 'Equador', 'Grupo E'),
('ECU-7', 'Joel Ordóñez', 'Equador', 'Grupo E'),
('ECU-8', 'Moisés Caicedo', 'Equador', 'Grupo E'),
('ECU-9', 'Alan Franco', 'Equador', 'Grupo E'),
('ECU-10', 'Kendry Páez', 'Equador', 'Grupo E'),
('ECU-11', 'Pedro Vite', 'Equador', 'Grupo E'),
('ECU-12', 'John Veboah', 'Equador', 'Grupo E'),
('ECU-13', 'Leonardo Campana', 'Equador', 'Grupo E'),
('ECU-14', 'Gonzalo Plata', 'Equador', 'Grupo E'),
('ECU-15', 'Nilson Angulo', 'Equador', 'Grupo E'),
('ECU-16', 'Alan Minda', 'Equador', 'Grupo E'),
('ECU-17', 'Kevin Rodríguez', 'Equador', 'Grupo E'),
('ECU-18', 'Enner Valencia', 'Equador', 'Grupo E'),
('NED-1', 'Bart Verbruggen', 'Holanda', 'Grupo F'),
('NED-2', 'Virgil van Dijk', 'Holanda', 'Grupo F'),
('NED-3', 'Micky van de Ven', 'Holanda', 'Grupo F'),
('NED-4', 'Jurriën Timber', 'Holanda', 'Grupo F'),
('NED-5', 'Denzel Dumfries', 'Holanda', 'Grupo F'),
('NED-6', 'Nathan Aké', 'Holanda', 'Grupo F'),
('NED-7', 'Jeremie Frimpong', 'Holanda', 'Grupo F'),
('NED-8', 'Jan Paul van Hecke', 'Holanda', 'Grupo F'),
('NED-9', 'Tijjani Reijnders', 'Holanda', 'Grupo F'),
('NED-10', 'Ryan Gravenberch', 'Holanda', 'Grupo F'),
('NED-11', 'Teun Koopmeiners', 'Holanda', 'Grupo F'),
('NED-12', 'Frenkie de Jong', 'Holanda', 'Grupo F'),
('NED-13', 'Xavi Simons', 'Holanda', 'Grupo F'),
('NED-14', 'Justin Kluivert', 'Holanda', 'Grupo F'),
('NED-15', 'Memphis Depay', 'Holanda', 'Grupo F'),
('NED-16', 'Donyell Malen', 'Holanda', 'Grupo F'),
('NED-17', 'Wout Weghorst', 'Holanda', 'Grupo F'),
('NED-18', 'Cody Gakpo', 'Holanda', 'Grupo F'),
('JPN-1', 'Zion Suzuki', 'Japão', 'Grupo F'),
('JPN-2', 'Henry Heroki Mochizuki', 'Japão', 'Grupo F'),
('JPN-3', 'Ayumu Seko', 'Japão', 'Grupo F'),
('JPN-4', 'Junnosuke Suzuki', 'Japão', 'Grupo F'),
('JPN-5', 'Shogo Taniguchi', 'Japão', 'Grupo F'),
('JPN-6', 'Tsuyoshi Watanabe', 'Japão', 'Grupo F'),
('JPN-7', 'Kaishu Sano', 'Japão', 'Grupo F'),
('JPN-8', 'Yuki Soma', 'Japão', 'Grupo F'),
('JPN-9', 'Ao Tanaka', 'Japão', 'Grupo F'),
('JPN-10', 'Daichi Kamada', 'Japão', 'Grupo F'),
('JPN-11', 'Takefusa Kubo', 'Japão', 'Grupo F'),
('JPN-12', 'Ritsu Doan', 'Japão', 'Grupo F'),
('JPN-13', 'Keito Nakamura', 'Japão', 'Grupo F'),
('JPN-14', 'Takumi Minamino', 'Japão', 'Grupo F'),
('JPN-15', 'Shuto Machino', 'Japão', 'Grupo F'),
('JPN-16', 'Junya Ito', 'Japão', 'Grupo F'),
('JPN-17', 'Koki Ogawa', 'Japão', 'Grupo F'),
('JPN-18', 'Ayase Ueda', 'Japão', 'Grupo F'),
('SWE-1', 'Victor Johansson', 'Suécia', 'Grupo F'),
('SWE-2', 'Isak Hien', 'Suécia', 'Grupo F'),
('SWE-3', 'Gabriel Gudmundsson', 'Suécia', 'Grupo F'),
('SWE-4', 'Emil Holm', 'Suécia', 'Grupo F'),
('SWE-5', 'Victor Nilsson Lindelöf', 'Suécia', 'Grupo F'),
('SWE-6', 'Gustaf Lagerbielke', 'Suécia', 'Grupo F'),
('SWE-7', 'Lucas Bergvall', 'Suécia', 'Grupo F'),
('SWE-8', 'Hugo Larsson', 'Suécia', 'Grupo F'),
('SWE-9', 'Jesper Karlström', 'Suécia', 'Grupo F'),
('SWE-10', 'Yasin Ayari', 'Suécia', 'Grupo F'),
('SWE-11', 'Mattias Svanberg', 'Suécia', 'Grupo F'),
('SWE-12', 'Daniel Svensson', 'Suécia', 'Grupo F'),
('SWE-13', 'Ken Sema', 'Suécia', 'Grupo F'),
('SWE-14', 'Roony Bardghji', 'Suécia', 'Grupo F'),
('SWE-15', 'Dejan Kulusevski', 'Suécia', 'Grupo F'),
('SWE-16', 'Anthony Elanga', 'Suécia', 'Grupo F'),
('SWE-17', 'Alexander Isak', 'Suécia', 'Grupo F'),
('SWE-18', 'Viktor Gyökeres', 'Suécia', 'Grupo F'),
('TUN-1', 'Bechir Ben Said', 'Tunísia', 'Grupo F'),
('TUN-2', 'Aymen Dahmen', 'Tunísia', 'Grupo F'),
('TUN-3', 'Van Valery', 'Tunísia', 'Grupo F'),
('TUN-4', 'Montassar Talbi', 'Tunísia', 'Grupo F'),
('TUN-5', 'Yassine Meriah', 'Tunísia', 'Grupo F'),
('TUN-6', 'Ali Abdi', 'Tunísia', 'Grupo F'),
('TUN-7', 'Dylan Bronn', 'Tunísia', 'Grupo F'),
('TUN-8', 'Ellyes Skhiri', 'Tunísia', 'Grupo F'),
('TUN-9', 'Aissa Laidouni', 'Tunísia', 'Grupo F'),
('TUN-10', 'Ferjani Sassi', 'Tunísia', 'Grupo F'),
('TUN-11', 'Mohamed Ali Ben Romdhane', 'Tunísia', 'Grupo F'),
('TUN-12', 'Hannibal Mejbri', 'Tunísia', 'Grupo F'),
('TUN-13', 'Elias Achouri', 'Tunísia', 'Grupo F'),
('TUN-14', 'Elias Saad', 'Tunísia', 'Grupo F'),
('TUN-15', 'Hazem Mastouri', 'Tunísia', 'Grupo F'),
('TUN-16', 'Ismael Gharbi', 'Tunísia', 'Grupo F'),
('TUN-17', 'Sayfallah Ltaief', 'Tunísia', 'Grupo F'),
('TUN-18', 'Naim Sliti', 'Tunísia', 'Grupo F'),
('BEL-1', 'Thibaut Courtois', 'Bélgica', 'Grupo G'),
('BEL-2', 'Arthur Theate', 'Bélgica', 'Grupo G'),
('BEL-3', 'Timothy Castagne', 'Bélgica', 'Grupo G'),
('BEL-4', 'Zeno Debast', 'Bélgica', 'Grupo G'),
('BEL-5', 'Brandon Mechele', 'Bélgica', 'Grupo G'),
('BEL-6', 'Maxim De Cuyper', 'Bélgica', 'Grupo G'),
('BEL-7', 'Thomas Meunier', 'Bélgica', 'Grupo G'),
('BEL-8', 'Youri Tielemans', 'Bélgica', 'Grupo G'),
('BEL-9', 'Amadou Onana', 'Bélgica', 'Grupo G'),
('BEL-10', 'Nicolas Raskin', 'Bélgica', 'Grupo G'),
('BEL-11', 'Alexis Saelemaekers', 'Bélgica', 'Grupo G'),
('BEL-12', 'Hans Vanaken', 'Bélgica', 'Grupo G'),
('BEL-13', 'Kevin De Bruyne', 'Bélgica', 'Grupo G'),
('BEL-14', 'Jérémy Doku', 'Bélgica', 'Grupo G'),
('BEL-15', 'Charles De Ketelaere', 'Bélgica', 'Grupo G'),
('BEL-16', 'Leandro Trossard', 'Bélgica', 'Grupo G'),
('BEL-17', 'Loïs Openda', 'Bélgica', 'Grupo G'),
('BEL-18', 'Romelu Lukaku', 'Bélgica', 'Grupo G'),
('EGY-1', 'Mohamed El Shenawy', 'Egito', 'Grupo G'),
('EGY-2', 'Mohamed Hany', 'Egito', 'Grupo G'),
('EGY-3', 'Mohamed Hamdy', 'Egito', 'Grupo G'),
('EGY-4', 'Yasser Ibrahim', 'Egito', 'Grupo G'),
('EGY-5', 'Khaled Sobhi', 'Egito', 'Grupo G'),
('EGY-6', 'Ramy Rabia', 'Egito', 'Grupo G'),
('EGY-7', 'Hossam Abdelmaguid', 'Egito', 'Grupo G'),
('EGY-8', 'Ahmed Fatouh', 'Egito', 'Grupo G'),
('EGY-9', 'Marwan Attia', 'Egito', 'Grupo G'),
('EGY-10', 'Zizo', 'Egito', 'Grupo G'),
('EGY-11', 'Hamdy Fathy', 'Egito', 'Grupo G'),
('EGY-12', 'Mohamed Lasheen', 'Egito', 'Grupo G'),
('EGY-13', 'Emam Ashour', 'Egito', 'Grupo G'),
('EGY-14', 'Osama Faisal', 'Egito', 'Grupo G'),
('EGY-15', 'Mohamed Salah', 'Egito', 'Grupo G'),
('EGY-16', 'Mostafa Mohamed', 'Egito', 'Grupo G'),
('EGY-17', 'Trezeguet', 'Egito', 'Grupo G'),
('EGY-18', 'Omar Marmoush', 'Egito', 'Grupo G'),
('IRN-1', 'Alireza Beiranvand', 'Irã', 'Grupo G'),
('IRN-2', 'Morteza Pouraliganji', 'Irã', 'Grupo G'),
('IRN-3', 'Ehsan Hajsafi', 'Irã', 'Grupo G'),
('IRN-4', 'Milad Mohammadi', 'Irã', 'Grupo G'),
('IRN-5', 'Shoja Khalilzadeh', 'Irã', 'Grupo G'),
('IRN-6', 'Ramin Rezaeian', 'Irã', 'Grupo G'),
('IRN-7', 'Hossein Kanaani', 'Irã', 'Grupo G'),
('IRN-8', 'Sadegh Moharrami', 'Irã', 'Grupo G'),
('IRN-9', 'Saleh Hardani', 'Irã', 'Grupo G'),
('IRN-10', 'Saeed Ezatolahi', 'Irã', 'Grupo G'),
('IRN-11', 'Saman Ghoddos', 'Irã', 'Grupo G'),
('IRN-12', 'Omid Noorafkan', 'Irã', 'Grupo G'),
('IRN-13', 'Roozbeh Cheshmi', 'Irã', 'Grupo G'),
('IRN-14', 'Mohammad Mohebi', 'Irã', 'Grupo G'),
('IRN-15', 'Sardar Azmoun', 'Irã', 'Grupo G'),
('IRN-16', 'Mehdi Taremi', 'Irã', 'Grupo G'),
('IRN-17', 'Alireza Jahanbakhsh', 'Irã', 'Grupo G'),
('IRN-18', 'Ali Gholizadeh', 'Irã', 'Grupo G'),
('NZL-1', 'Max Crocombe-Payne', 'Nova Zelândia', 'Grupo G'),
('NZL-2', 'Alex Paulsen', 'Nova Zelândia', 'Grupo G'),
('NZL-3', 'Michael Boxall', 'Nova Zelândia', 'Grupo G'),
('NZL-4', 'Liberato Cacace', 'Nova Zelândia', 'Grupo G'),
('NZL-5', 'Tim Payne', 'Nova Zelândia', 'Grupo G'),
('NZL-6', 'Tyler Bindon', 'Nova Zelândia', 'Grupo G'),
('NZL-7', 'Francis de Vries', 'Nova Zelândia', 'Grupo G'),
('NZL-8', 'Finn Surman', 'Nova Zelândia', 'Grupo G'),
('NZL-9', 'Joe Bell', 'Nova Zelândia', 'Grupo G'),
('NZL-10', 'Sarpreet Singh', 'Nova Zelândia', 'Grupo G'),
('NZL-11', 'Ryan Thomas', 'Nova Zelândia', 'Grupo G'),
('NZL-12', 'Matthew Garbett', 'Nova Zelândia', 'Grupo G'),
('NZL-13', 'Marko Stamenić', 'Nova Zelândia', 'Grupo G'),
('NZL-14', 'Ben Old', 'Nova Zelândia', 'Grupo G'),
('NZL-15', 'Chris Wood', 'Nova Zelândia', 'Grupo G'),
('NZL-16', 'Elijah Just', 'Nova Zelândia', 'Grupo G'),
('NZL-17', 'Callum McCowatt', 'Nova Zelândia', 'Grupo G'),
('NZL-18', 'Kosta Barbarouses', 'Nova Zelândia', 'Grupo G'),
('ESP-1', 'Unai Simón', 'Espanha', 'Grupo H'),
('ESP-2', 'Robin Le Normand', 'Espanha', 'Grupo H'),
('ESP-3', 'Aymeric Laporte', 'Espanha', 'Grupo H'),
('ESP-4', 'Dean Huijsen', 'Espanha', 'Grupo H'),
('ESP-5', 'Pedro Porro', 'Espanha', 'Grupo H'),
('ESP-6', 'Dani Carvajal', 'Espanha', 'Grupo H'),
('ESP-7', 'Marc Cucurella', 'Espanha', 'Grupo H'),
('ESP-8', 'Martín Zubimendi', 'Espanha', 'Grupo H'),
('ESP-9', 'Rodri', 'Espanha', 'Grupo H'),
('ESP-10', 'Pedri', 'Espanha', 'Grupo H'),
('ESP-11', 'Fabián Ruiz', 'Espanha', 'Grupo H'),
('ESP-12', 'Mikel Merino', 'Espanha', 'Grupo H'),
('ESP-13', 'Lamine Yamal', 'Espanha', 'Grupo H'),
('ESP-14', 'Dani Olmo', 'Espanha', 'Grupo H'),
('ESP-15', 'Nico Williams', 'Espanha', 'Grupo H'),
('ESP-16', 'Ferran Torres', 'Espanha', 'Grupo H'),
('ESP-17', 'Álvaro Morata', 'Espanha', 'Grupo H'),
('ESP-18', 'Mikel Oyarzabal', 'Espanha', 'Grupo H'),
('CPV-1', 'Vozinha', 'Cabo Verde', 'Grupo H'),
('CPV-2', 'Logan Costa', 'Cabo Verde', 'Grupo H'),
('CPV-3', 'Pico', 'Cabo Verde', 'Grupo H'),
('CPV-4', 'Diney', 'Cabo Verde', 'Grupo H'),
('CPV-5', 'Steven Moreira', 'Cabo Verde', 'Grupo H'),
('CPV-6', 'Wagner Pina', 'Cabo Verde', 'Grupo H'),
('CPV-7', 'João Paulo', 'Cabo Verde', 'Grupo H'),
('CPV-8', 'Yannick Semedo', 'Cabo Verde', 'Grupo H'),
('CPV-9', 'Kevin Pina', 'Cabo Verde', 'Grupo H'),
('CPV-10', 'Patrick Andrade', 'Cabo Verde', 'Grupo H'),
('CPV-11', 'Jamiro Monteiro', 'Cabo Verde', 'Grupo H'),
('CPV-12', 'Deroy Duarte', 'Cabo Verde', 'Grupo H'),
('CPV-13', 'Garry Rodrigues', 'Cabo Verde', 'Grupo H'),
('CPV-14', 'Jovane Cabral', 'Cabo Verde', 'Grupo H'),
('CPV-15', 'Ryan Mendes', 'Cabo Verde', 'Grupo H'),
('CPV-16', 'Dailon Livramento', 'Cabo Verde', 'Grupo H'),
('CPV-17', 'Willy Semedo', 'Cabo Verde', 'Grupo H'),
('CPV-18', 'Bebé', 'Cabo Verde', 'Grupo H'),
('KSA-1', 'Nawaf Alaqidi', 'Arábia Saudita', 'Grupo H'),
('KSA-2', 'Abdulrahman Al-Sanbi', 'Arábia Saudita', 'Grupo H'),
('KSA-3', 'Saud Abdulhamid', 'Arábia Saudita', 'Grupo H'),
('KSA-4', 'Nawaf Boushal', 'Arábia Saudita', 'Grupo H'),
('KSA-5', 'Jihad Thakri', 'Arábia Saudita', 'Grupo H'),
('KSA-6', 'Moteb Al-Harbi', 'Arábia Saudita', 'Grupo H'),
('KSA-7', 'Hassan Altambakti', 'Arábia Saudita', 'Grupo H'),
('KSA-8', 'Musab Aljuwayr', 'Arábia Saudita', 'Grupo H'),
('KSA-9', 'Ziyad Aljohani', 'Arábia Saudita', 'Grupo H'),
('KSA-10', 'Abdullah Alkhaibari', 'Arábia Saudita', 'Grupo H'),
('KSA-11', 'Nasser Aldawsari', 'Arábia Saudita', 'Grupo H'),
('KSA-12', 'Saleh Abu Alshamat', 'Arábia Saudita', 'Grupo H'),
('KSA-13', 'Marwan Alsahafi', 'Arábia Saudita', 'Grupo H'),
('KSA-14', 'Salem Aldawsari', 'Arábia Saudita', 'Grupo H'),
('KSA-15', 'Abdulrahman Al-Aboud', 'Arábia Saudita', 'Grupo H'),
('KSA-16', 'Feras Albrikan', 'Arábia Saudita', 'Grupo H'),
('KSA-17', 'Saleh Alshehri', 'Arábia Saudita', 'Grupo H'),
('KSA-18', 'Abdullah Al-Hamdan', 'Arábia Saudita', 'Grupo H'),
('URU-1', 'Sergio Rochet', 'Uruguai', 'Grupo H'),
('URU-2', 'Santiago Mele', 'Uruguai', 'Grupo H'),
('URU-3', 'Ronald Araujo', 'Uruguai', 'Grupo H'),
('URU-4', 'José María Giménez', 'Uruguai', 'Grupo H'),
('URU-5', 'Sebastian Caceres', 'Uruguai', 'Grupo H'),
('URU-6', 'Mathias Olivera', 'Uruguai', 'Grupo H'),
('URU-7', 'Guillermo Varela', 'Uruguai', 'Grupo H'),
('URU-8', 'Nahitan Nandez', 'Uruguai', 'Grupo H'),
('URU-9', 'Federico Valverde', 'Uruguai', 'Grupo H'),
('URU-10', 'Giorgian De Arrascaeta', 'Uruguai', 'Grupo H'),
('URU-11', 'Rodrigo Bentancur', 'Uruguai', 'Grupo H'),
('URU-12', 'Manuel Ugarte', 'Uruguai', 'Grupo H'),
('URU-13', 'Nicolás de la Cruz', 'Uruguai', 'Grupo H'),
('URU-14', 'Maxi Araujo', 'Uruguai', 'Grupo H'),
('URU-15', 'Darwin Núñez', 'Uruguai', 'Grupo H'),
('URU-16', 'Federico Viñas', 'Uruguai', 'Grupo H'),
('URU-17', 'Rodrigo Aguirre', 'Uruguai', 'Grupo H'),
('URU-18', 'Facundo Pellistri', 'Uruguai', 'Grupo H'),
('FRA-1', 'Mike Maignan', 'França', 'Grupo I'),
('FRA-2', 'Theo Hernández', 'França', 'Grupo I'),
('FRA-3', 'William Saliba', 'França', 'Grupo I'),
('FRA-4', 'Jules Koundé', 'França', 'Grupo I'),
('FRA-5', 'Ibrahima Konaté', 'França', 'Grupo I'),
('FRA-6', 'Dayot Upamecano', 'França', 'Grupo I'),
('FRA-7', 'Lucas Digne', 'França', 'Grupo I'),
('FRA-8', 'Aurélien Tchouaméni', 'França', 'Grupo I'),
('FRA-9', 'Eduardo Camavinga', 'França', 'Grupo I'),
('FRA-10', 'Manu Koné', 'França', 'Grupo I'),
('FRA-11', 'Adrien Rabiot', 'França', 'Grupo I'),
('FRA-12', 'Michael Olise', 'França', 'Grupo I'),
('FRA-13', 'Ousmane Dembélé', 'França', 'Grupo I'),
('FRA-14', 'Bradley Barcola', 'França', 'Grupo I'),
('FRA-15', 'Désiré Doué', 'França', 'Grupo I'),
('FRA-16', 'Kingsley Coman', 'França', 'Grupo I'),
('FRA-17', 'Hugo Ekitike', 'França', 'Grupo I'),
('FRA-18', 'Kylian Mbappé', 'França', 'Grupo I'),
('SEN-1', 'Eduardo Mendy', 'Senegal', 'Grupo I'),
('SEN-2', 'Yehvann Diouf', 'Senegal', 'Grupo I'),
('SEN-3', 'Moussa Niakhaté', 'Senegal', 'Grupo I'),
('SEN-4', 'Abdoulaye Seck', 'Senegal', 'Grupo I'),
('SEN-5', 'Ismail Jakobs', 'Senegal', 'Grupo I'),
('SEN-6', 'El Hadji Malick Diouf', 'Senegal', 'Grupo I'),
('SEN-7', 'Kalidou Koulibaly', 'Senegal', 'Grupo I'),
('SEN-8', 'Idrissa Gana Gueye', 'Senegal', 'Grupo I'),
('SEN-9', 'Pape Matar Sarr', 'Senegal', 'Grupo I'),
('SEN-10', 'Pape Gueye', 'Senegal', 'Grupo I'),
('SEN-11', 'Habib Diarra', 'Senegal', 'Grupo I'),
('SEN-12', 'Lamine Camara', 'Senegal', 'Grupo I'),
('SEN-13', 'Sadio Mane', 'Senegal', 'Grupo I'),
('SEN-14', 'Ismaïla Sarr', 'Senegal', 'Grupo I'),
('SEN-15', 'Boulaye Dia', 'Senegal', 'Grupo I'),
('SEN-16', 'Iliman Ndiaye', 'Senegal', 'Grupo I'),
('SEN-17', 'Nicolas Jackson', 'Senegal', 'Grupo I'),
('SEN-18', 'Krepin Diatta', 'Senegal', 'Grupo I'),
('IRQ-1', 'Jalal Hassan', 'Iraque', 'Grupo I'),
('IRQ-2', 'Rebin Sulaka', 'Iraque', 'Grupo I'),
('IRQ-3', 'Hussein Ali', 'Iraque', 'Grupo I'),
('IRQ-4', 'Akam Hashem', 'Iraque', 'Grupo I'),
('IRQ-5', 'Merchas Doski', 'Iraque', 'Grupo I'),
('IRQ-6', 'Zaid Tahseen', 'Iraque', 'Grupo I'),
('IRQ-7', 'Manaf Younis', 'Iraque', 'Grupo I'),
('IRQ-8', 'Zidane Iqbal', 'Iraque', 'Grupo I'),
('IRQ-9', 'Amir Al-Ammari', 'Iraque', 'Grupo I'),
('IRQ-10', 'Ibrahim Bayesh', 'Iraque', 'Grupo I'),
('IRQ-11', 'Ali Jasim', 'Iraque', 'Grupo I'),
('IRQ-12', 'Youssef Amyn', 'Iraque', 'Grupo I'),
('IRQ-13', 'Aimar Sher', 'Iraque', 'Grupo I'),
('IRQ-14', 'Marko Farji', 'Iraque', 'Grupo I'),
('IRQ-15', 'Osama Rashid', 'Iraque', 'Grupo I'),
('IRQ-16', 'Ali Al-Hamadi', 'Iraque', 'Grupo I'),
('IRQ-17', 'Aymen Hussein', 'Iraque', 'Grupo I'),
('IRQ-18', 'Mohanad Ali', 'Iraque', 'Grupo I'),
('NOR-1', 'Ørjan Nyland', 'Noruega', 'Grupo I'),
('NOR-2', 'Julian Ryerson', 'Noruega', 'Grupo I'),
('NOR-3', 'Leo Østigård', 'Noruega', 'Grupo I'),
('NOR-4', 'Kristoffer Ajer', 'Noruega', 'Grupo I'),
('NOR-5', 'Marcus Holmgren Pedersen', 'Noruega', 'Grupo I'),
('NOR-6', 'David Møller Wolfe', 'Noruega', 'Grupo I'),
('NOR-7', 'Torbjørn Heggem', 'Noruega', 'Grupo I'),
('NOR-8', 'Morten Thorsby', 'Noruega', 'Grupo I'),
('NOR-9', 'Martin Ødegaard', 'Noruega', 'Grupo I'),
('NOR-10', 'Sander Berge', 'Noruega', 'Grupo I'),
('NOR-11', 'Andreas Schjelderup', 'Noruega', 'Grupo I'),
('NOR-12', 'Patrick Berg', 'Noruega', 'Grupo I'),
('NOR-13', 'Erling Haaland', 'Noruega', 'Grupo I'),
('NOR-14', 'Alexander Sørloth', 'Noruega', 'Grupo I'),
('NOR-15', 'Aron Dønnum', 'Noruega', 'Grupo I'),
('NOR-16', 'Jørgen Strand Larsen', 'Noruega', 'Grupo I'),
('NOR-17', 'Antonio Nusa', 'Noruega', 'Grupo I'),
('NOR-18', 'Oscar Bobb', 'Noruega', 'Grupo I'),
('ARG-1', 'Emiliano Martínez', 'Argentina', 'Grupo J'),
('ARG-2', 'Nahuel Molina', 'Argentina', 'Grupo J'),
('ARG-3', 'Cristian Romero', 'Argentina', 'Grupo J'),
('ARG-4', 'Nicolás Otamendi', 'Argentina', 'Grupo J'),
('ARG-5', 'Nicolás Tagliafico', 'Argentina', 'Grupo J'),
('ARG-6', 'Leonardo Balerdi', 'Argentina', 'Grupo J'),
('ARG-7', 'Enzo Fernández', 'Argentina', 'Grupo J'),
('ARG-8', 'Alexis Mac Allister', 'Argentina', 'Grupo J'),
('ARG-9', 'Rodrigo De Paul', 'Argentina', 'Grupo J'),
('ARG-10', 'Exequiel Palacios', 'Argentina', 'Grupo J'),
('ARG-11', 'Leandro Paredes', 'Argentina', 'Grupo J'),
('ARG-12', 'Nico Paz', 'Argentina', 'Grupo J'),
('ARG-13', 'Franco Mastantuono', 'Argentina', 'Grupo J'),
('ARG-14', 'Nico González', 'Argentina', 'Grupo J'),
('ARG-15', 'Lionel Messi', 'Argentina', 'Grupo J'),
('ARG-16', 'Lautaro Martínez', 'Argentina', 'Grupo J'),
('ARG-17', 'Julián Álvarez', 'Argentina', 'Grupo J'),
('ARG-18', 'Giuliano Simeone', 'Argentina', 'Grupo J'),
('ALG-1', 'Alexis Guendouz', 'Argélia', 'Grupo J'),
('ALG-2', 'Ramy Bensebaini', 'Argélia', 'Grupo J'),
('ALG-3', 'Youcef Atal', 'Argélia', 'Grupo J'),
('ALG-4', 'Rayan Aït-Nouri', 'Argélia', 'Grupo J'),
('ALG-5', 'Mohamed Amine Tougai', 'Argélia', 'Grupo J'),
('ALG-6', 'Aïssa Mandi', 'Argélia', 'Grupo J'),
('ALG-7', 'Ismael Bennacer', 'Argélia', 'Grupo J'),
('ALG-8', 'Houssem Aouar', 'Argélia', 'Grupo J'),
('ALG-9', 'Hicham Boudaoui', 'Argélia', 'Grupo J'),
('ALG-10', 'Ramiz Zerrouki', 'Argélia', 'Grupo J'),
('ALG-11', 'Nabil Bentaleb', 'Argélia', 'Grupo J'),
('ALG-12', 'Farés Chaibi', 'Argélia', 'Grupo J'),
('ALG-13', 'Riyad Mahrez', 'Argélia', 'Grupo J'),
('ALG-14', 'Said Benrahma', 'Argélia', 'Grupo J'),
('ALG-15', 'Anis Hadj Moussa', 'Argélia', 'Grupo J'),
('ALG-16', 'Amine Gouiri', 'Argélia', 'Grupo J'),
('ALG-17', 'Baghdad Bounedjah', 'Argélia', 'Grupo J'),
('ALG-18', 'Mohammed Amoura', 'Argélia', 'Grupo J'),
('AUT-1', 'Alexander Schlager', 'Áustria', 'Grupo J'),
('AUT-2', 'Patrick Pentz', 'Áustria', 'Grupo J'),
('AUT-3', 'David Alaba', 'Áustria', 'Grupo J'),
('AUT-4', 'Kevin Danso', 'Áustria', 'Grupo J'),
('AUT-5', 'Philipp Lienhart', 'Áustria', 'Grupo J'),
('AUT-6', 'Stefan Posch', 'Áustria', 'Grupo J'),
('AUT-7', 'Phillipp Mwene', 'Áustria', 'Grupo J'),
('AUT-8', 'Alexander Prass', 'Áustria', 'Grupo J'),
('AUT-9', 'Xaver Schlager', 'Áustria', 'Grupo J'),
('AUT-10', 'Marcel Sabitzer', 'Áustria', 'Grupo J'),
('AUT-11', 'Konrad Laimer', 'Áustria', 'Grupo J'),
('AUT-12', 'Florian Grillitsch', 'Áustria', 'Grupo J'),
('AUT-13', 'Nicolas Seiwald', 'Áustria', 'Grupo J'),
('AUT-14', 'Romano Schmid', 'Áustria', 'Grupo J'),
('AUT-15', 'Patrick Wimmer', 'Áustria', 'Grupo J'),
('AUT-16', 'Christoph Baumgartner', 'Áustria', 'Grupo J'),
('AUT-17', 'Michael Gregoritsch', 'Áustria', 'Grupo J'),
('AUT-18', 'Marko Arnautović', 'Áustria', 'Grupo J'),
('JOR-1', 'Yazeed Abulaila', 'Jordânia', 'Grupo J'),
('JOR-2', 'Ihsan Haddad', 'Jordânia', 'Grupo J'),
('JOR-3', 'Mohammad Abu Hashish', 'Jordânia', 'Grupo J'),
('JOR-4', 'Yazan Al-Arab', 'Jordânia', 'Grupo J'),
('JOR-5', 'Abdallah Nasib', 'Jordânia', 'Grupo J'),
('JOR-6', 'Saleem Obaid', 'Jordânia', 'Grupo J'),
('JOR-7', 'Mohammad Abualnadi', 'Jordânia', 'Grupo J'),
('JOR-8', 'Ibrahim Saadeh', 'Jordânia', 'Grupo J'),
('JOR-9', 'Nizar Al-Rashdan', 'Jordânia', 'Grupo J'),
('JOR-10', 'Noor Al-Rawabdeh', 'Jordânia', 'Grupo J'),
('JOR-11', 'Mohannad Abu Taha', 'Jordânia', 'Grupo J'),
('JOR-12', 'Amer Jamous', 'Jordânia', 'Grupo J'),
('JOR-13', 'Musa Al-Taamari', 'Jordânia', 'Grupo J'),
('JOR-14', 'Yazan Al-Naimat', 'Jordânia', 'Grupo J'),
('JOR-15', 'Mahmoud Al-Mardi', 'Jordânia', 'Grupo J'),
('JOR-16', 'Ali Olwan', 'Jordânia', 'Grupo J'),
('JOR-17', 'Mohammad Abu Zrayq', 'Jordânia', 'Grupo J'),
('JOR-18', 'Ibrahim Sabra', 'Jordânia', 'Grupo J'),
('POR-1', 'Diogo Costa', 'Portugal', 'Grupo K'),
('POR-2', 'Jose Sa', 'Portugal', 'Grupo K'),
('POR-3', 'Ruben Dias', 'Portugal', 'Grupo K'),
('POR-4', 'João Cancelo', 'Portugal', 'Grupo K'),
('POR-5', 'Diogo Dalot', 'Portugal', 'Grupo K'),
('POR-6', 'Nuno Mendes', 'Portugal', 'Grupo K'),
('POR-7', 'Gonçalo Inácio', 'Portugal', 'Grupo K'),
('POR-8', 'Bernardo Silva', 'Portugal', 'Grupo K'),
('POR-9', 'Bruno Fernandes', 'Portugal', 'Grupo K'),
('POR-10', 'Ruben Neves', 'Portugal', 'Grupo K'),
('POR-11', 'Vitinha', 'Portugal', 'Grupo K'),
('POR-12', 'João Neves', 'Portugal', 'Grupo K'),
('POR-13', 'Cristiano Ronaldo', 'Portugal', 'Grupo K'),
('POR-14', 'Francisco Trincão', 'Portugal', 'Grupo K'),
('POR-15', 'João Felix', 'Portugal', 'Grupo K'),
('POR-16', 'Gonçalo Ramos', 'Portugal', 'Grupo K'),
('POR-17', 'Pedro Neto', 'Portugal', 'Grupo K'),
('POR-18', 'Rafael Leão', 'Portugal', 'Grupo K'),
('COD-1', 'Lionel Mpasi', 'RD Congo', 'Grupo K'),
('COD-2', 'Aaron Wan-Bissaka', 'RD Congo', 'Grupo K'),
('COD-3', 'Axel Tuanzebe', 'RD Congo', 'Grupo K'),
('COD-4', 'Arthur Masuaku', 'RD Congo', 'Grupo K'),
('COD-5', 'Chancel Mbemba', 'RD Congo', 'Grupo K'),
('COD-6', 'Joris Kayembe', 'RD Congo', 'Grupo K'),
('COD-7', 'Charles Pickel', 'RD Congo', 'Grupo K'),
('COD-8', 'Ngal’ayel Mukau', 'RD Congo', 'Grupo K'),
('COD-9', 'Edo Kayembe', 'RD Congo', 'Grupo K'),
('COD-10', 'Samuel Moutoussamy', 'RD Congo', 'Grupo K'),
('COD-11', 'Noah Sadiki', 'RD Congo', 'Grupo K'),
('COD-12', 'Théo Bongonda', 'RD Congo', 'Grupo K'),
('COD-13', 'Meschack Elia', 'RD Congo', 'Grupo K'),
('COD-14', 'Yoane Wissa', 'RD Congo', 'Grupo K'),
('COD-15', 'Brian Cipenga', 'RD Congo', 'Grupo K'),
('COD-16', 'Fiston Mayele', 'RD Congo', 'Grupo K'),
('COD-17', 'Cédric Bakambu', 'RD Congo', 'Grupo K'),
('COD-18', 'Nathanaël Mbuku', 'RD Congo', 'Grupo K'),
('UZB-1', 'Utkir Yusupov', 'Uzbequistão', 'Grupo K'),
('UZB-2', 'Farrukh Savfiev', 'Uzbequistão', 'Grupo K'),
('UZB-3', 'Sherzod Nasrullaev', 'Uzbequistão', 'Grupo K'),
('UZB-4', 'Umar Eshmurodov', 'Uzbequistão', 'Grupo K'),
('UZB-5', 'Husniddin Aliqulov', 'Uzbequistão', 'Grupo K'),
('UZB-6', 'Rustamjon Ashurmatov', 'Uzbequistão', 'Grupo K'),
('UZB-7', 'Khojiakbar Alijonov', 'Uzbequistão', 'Grupo K'),
('UZB-8', 'Abdukodir Khusanov', 'Uzbequistão', 'Grupo K'),
('UZB-9', 'Odiljon Hamrobekov', 'Uzbequistão', 'Grupo K'),
('UZB-10', 'Otabek Shukurov', 'Uzbequistão', 'Grupo K'),
('UZB-11', 'Jamshid Iskanderov', 'Uzbequistão', 'Grupo K'),
('UZB-12', 'Azizbek Turgunboev', 'Uzbequistão', 'Grupo K'),
('UZB-13', 'Khojimat Erkinov', 'Uzbequistão', 'Grupo K'),
('UZB-14', 'Eldor Shomurodov', 'Uzbequistão', 'Grupo K'),
('UZB-15', 'Oston Urunov', 'Uzbequistão', 'Grupo K'),
('UZB-16', 'Jaloliddin Masharipov', 'Uzbequistão', 'Grupo K'),
('UZB-17', 'Igor Sergeev', 'Uzbequistão', 'Grupo K'),
('UZB-18', 'Abbosbek Fayzullaev', 'Uzbequistão', 'Grupo K'),
('COL-1', 'Camilo Vargas', 'Colômbia', 'Grupo K'),
('COL-2', 'David Ospina', 'Colômbia', 'Grupo K'),
('COL-3', 'Dávinson Sánchez', 'Colômbia', 'Grupo K'),
('COL-4', 'Yerry Mina', 'Colômbia', 'Grupo K'),
('COL-5', 'Daniel Muñoz', 'Colômbia', 'Grupo K'),
('COL-6', 'Johan Mojica', 'Colômbia', 'Grupo K'),
('COL-7', 'Jhon Lucumí', 'Colômbia', 'Grupo K'),
('COL-8', 'Santiago Arias', 'Colômbia', 'Grupo K'),
('COL-9', 'Jefferson Lerma', 'Colômbia', 'Grupo K'),
('COL-10', 'Kevin Castaño', 'Colômbia', 'Grupo K'),
('COL-11', 'Richard Ríos', 'Colômbia', 'Grupo K'),
('COL-12', 'James Rodríguez', 'Colômbia', 'Grupo K'),
('COL-13', 'Juan Fernando Quintero', 'Colômbia', 'Grupo K'),
('COL-14', 'Jorge Carrascal', 'Colômbia', 'Grupo K'),
('COL-15', 'Jhon Arias', 'Colômbia', 'Grupo K'),
('COL-16', 'Jhon Córdoba', 'Colômbia', 'Grupo K'),
('COL-17', 'Luis Suárez', 'Colômbia', 'Grupo K'),
('COL-18', 'Luis Díaz', 'Colômbia', 'Grupo K'),
('ENG-1', 'Jordan Pickford', 'Inglaterra', 'Grupo L'),
('ENG-2', 'John Stones', 'Inglaterra', 'Grupo L'),
('ENG-3', 'Marc Guéhi', 'Inglaterra', 'Grupo L'),
('ENG-4', 'Ezri Konsa', 'Inglaterra', 'Grupo L'),
('ENG-5', 'Trent Alexander-Arnold', 'Inglaterra', 'Grupo L'),
('ENG-6', 'Reece James', 'Inglaterra', 'Grupo L'),
('ENG-7', 'Dan Burn', 'Inglaterra', 'Grupo L'),
('ENG-8', 'Jordan Henderson', 'Inglaterra', 'Grupo L'),
('ENG-9', 'Declan Rice', 'Inglaterra', 'Grupo L'),
('ENG-10', 'Jude Bellingham', 'Inglaterra', 'Grupo L'),
('ENG-11', 'Cole Palmer', 'Inglaterra', 'Grupo L'),
('ENG-12', 'Morgan Rogers', 'Inglaterra', 'Grupo L'),
('ENG-13', 'Anthony Gordon', 'Inglaterra', 'Grupo L'),
('ENG-14', 'Phil Foden', 'Inglaterra', 'Grupo L'),
('ENG-15', 'Bukayo Saka', 'Inglaterra', 'Grupo L'),
('ENG-16', 'Harry Kane', 'Inglaterra', 'Grupo L'),
('ENG-17', 'Marcus Rashford', 'Inglaterra', 'Grupo L'),
('ENG-18', 'Ollie Watkins', 'Inglaterra', 'Grupo L'),
('CRO-1', 'Dominik Livaković', 'Croácia', 'Grupo L'),
('CRO-2', 'Duje Ćaleta-Car', 'Croácia', 'Grupo L'),
('CRO-3', 'Joško Gvardiol', 'Croácia', 'Grupo L'),
('CRO-4', 'Josip Stanišić', 'Croácia', 'Grupo L'),
('CRO-5', 'Luka Vušković', 'Croácia', 'Grupo L'),
('CRO-6', 'Josip Šutalo', 'Croácia', 'Grupo L'),
('CRO-7', 'Kristijan Jakić', 'Croácia', 'Grupo L'),
('CRO-8', 'Luka Modrić', 'Croácia', 'Grupo L'),
('CRO-9', 'Mateo Kovačić', 'Croácia', 'Grupo L'),
('CRO-10', 'Martin Baturina', 'Croácia', 'Grupo L'),
('CRO-11', 'Lovro Majer', 'Croácia', 'Grupo L'),
('CRO-12', 'Mario Pašalić', 'Croácia', 'Grupo L'),
('CRO-13', 'Petar Sučić', 'Croácia', 'Grupo L'),
('CRO-14', 'Ivan Perišić', 'Croácia', 'Grupo L'),
('CRO-15', 'Marco Pašalić', 'Croácia', 'Grupo L'),
('CRO-16', 'Ante Budimir', 'Croácia', 'Grupo L'),
('CRO-17', 'Andrej Kramarić', 'Croácia', 'Grupo L'),
('CRO-18', 'Franjo Ivanović', 'Croácia', 'Grupo L'),
('GHA-1', 'Lawrence Ati Zigi', 'Gana', 'Grupo L'),
('GHA-2', 'Tariq Lamptey', 'Gana', 'Grupo L'),
('GHA-3', 'Mohammed Salisu', 'Gana', 'Grupo L'),
('GHA-4', 'Alidu Seidu', 'Gana', 'Grupo L'),
('GHA-5', 'Alexander Djiku', 'Gana', 'Grupo L'),
('GHA-6', 'Gideon Mensah', 'Gana', 'Grupo L'),
('GHA-7', 'Caleb Yirenkyi', 'Gana', 'Grupo L'),
('GHA-8', 'Abdul Fatawu Issahaku', 'Gana', 'Grupo L'),
('GHA-9', 'Thomas Partey', 'Gana', 'Grupo L'),
('GHA-10', 'Salis Abdul Samed', 'Gana', 'Grupo L'),
('GHA-11', 'Kamaldeen Sulemana', 'Gana', 'Grupo L'),
('GHA-12', 'Mohammed Kudus', 'Gana', 'Grupo L'),
('GHA-13', 'Iñaki Williams', 'Gana', 'Grupo L'),
('GHA-14', 'Jordan Ayew', 'Gana', 'Grupo L'),
('GHA-15', 'André Ayew', 'Gana', 'Grupo L'),
('GHA-16', 'Joseph Paintsil', 'Gana', 'Grupo L'),
('GHA-17', 'Osman Bukari', 'Gana', 'Grupo L'),
('GHA-18', 'Antoine Semenyo', 'Gana', 'Grupo L'),
('PAN-1', 'Orlando Mosquera', 'Panamá', 'Grupo L'),
('PAN-2', 'Luis Mejía', 'Panamá', 'Grupo L'),
('PAN-3', 'Fidel Escobar', 'Panamá', 'Grupo L'),
('PAN-4', 'Andrés Andrade', 'Panamá', 'Grupo L'),
('PAN-5', 'Michael Amir Murillo', 'Panamá', 'Grupo L'),
('PAN-6', 'Eric Davis', 'Panamá', 'Grupo L'),
('PAN-7', 'José Córdoba', 'Panamá', 'Grupo L'),
('PAN-8', 'César Blackman', 'Panamá', 'Grupo L'),
('PAN-9', 'Cristian Martínez', 'Panamá', 'Grupo L'),
('PAN-10', 'Aníbal Godoy', 'Panamá', 'Grupo L'),
('PAN-11', 'Adalberto Carrasquilla', 'Panamá', 'Grupo L'),
('PAN-12', 'Édgar Bárcenas', 'Panamá', 'Grupo L'),
('PAN-13', 'Carlos Harvey', 'Panamá', 'Grupo L'),
('PAN-14', 'Ismael Díaz', 'Panamá', 'Grupo L'),
('PAN-15', 'José Fajardo', 'Panamá', 'Grupo L'),
('PAN-16', 'Cecilio Waterman', 'Panamá', 'Grupo L'),
('PAN-17', 'José Luis Rodríguez', 'Panamá', 'Grupo L'),
('PAN-18', 'Alberto Quintero', 'Panamá', 'Grupo L');
